- name: install redshift
  sudo: true
  dnf: "name={{ item }} state=present"
  with_items:
  - redshift
  - redshift-gtk

- name: configure redshift
  template:
    src=redshift.conf
    dest="{{ homedir }}/.config/redshift.conf"
    owner="{{ username }}"
    group="{{ username }}"
    mode=0700

- name: enable redshift service
  command: systemctl --user enable redshift-gtk.service

- name: start redshift service
  command: systemctl --user restart redshift-gtk.service

